exports.ADD_ERROR = 'ADD_ERROR';
exports.REMOVE_ERROR = 'REMOVE_ERROR';
exports.SET_CURRENT_USER = 'SET_CURRENT_USER'
exports.UPDATE_USER_SKILLS = 'UPDATE_USER_SKILLS'
exports.UPDATE_USER_CERTIFICATES = 'UPDATE_USER_CERTIFICATES'
exports.UPDATE_USER_INFO = 'UPDATE_USER_INFO'
exports.UPDATE_USER_BIO = 'UPDATE_USER_BIO'
exports.UPDATE_USER_BASIC_INFO = 'UPDATE_USER_BASIC_INFO'



